name: ECS Deploy Pipeline # name of GitHub actions pipeline

on:
  push:
    branches:
      - main # runs on main branch
      - feature/* # runs on any feature branch

jobs:
  deploy: ## deploy job
    runs-on: ubuntu-latest
    env:
      TF_LOG: DEBUG

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} ## access_key_id
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} ## secret_access_key
          aws-region: eu-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/